Dues\DuesBundle\Entity\Due:
    detect_relations: true
    type: entity
    manyToOne:
        holder_id:
            targetEntity: User
            joinColumn:
                name: holder_id
                referencedColumnName: id
        debtor_id: 
            targetEntity: Debtor
            joinColumn:
                name: debtor_id
                referencedColumnName: id
        
    table: dues
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    
    fields:
        amount: 
            type: float 
            nullable: false
    
        start_date: 
            type: date
    
        intrest_start: 
            type: date
        
        intrest_rate: 
            type: float
        
        due_list_id: integer
    
    
        
    
    