Dues\DuesBundle\Entity\Due:
    detect_relations: true
    type: entity
    manyToOne:
        holder_id:
            targetEntity: User
            joinColumn:
                name: holder_id
                referencedColumnName: id
        debtor_id: 
            targetEntity: Debtor
            joinColumn:
                name: debtor_id
                referencedColumnName: id
                nullable: false
        due_list_id:
            targetEntity: DueList
            joinColumn:
                name: due_list_id
                referencedColumnName: id
                nullable: false
        
    table: dues
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    
    fields:
        title:
            type: string
            nullable: true
        amount: 
            type: float 
            nullable: false
    
        start_date: 
            type: date
    
        intrest_start: 
            type: date
            nullalble: true
        
        intrest_rate: 
            type: float
            nullable: true
        
    
    
        
    
    