Dues\DuesBundle\Entity\Due:
    detect_relations: true
    type: entity
    table: dues
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    
    fields:
        amount: 
            type: float 
            nullable: false
    
        holder_id: 
            type: integer
    
        debtor_id: 
            type: integer
    
        start_date: 
            type: date
    
        intrest_start: 
            type: date
        
        intrest_rate: 
            type: float
        
        due_list_id: integer
    
    
        
    
    