Dues\DuesBundle\Entity\User:
    type:  entity
    table: due_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        display_name: 
            type: text
            length: 128
            nullable: True